# Generated by Django 3.2.6 on 2021-08-13 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'group_type',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal', models.CharField(blank=True, max_length=10, null=True)),
                ('bohoon_num', models.CharField(blank=True, max_length=15, null=True)),
                ('yoo_gong_ja_name', models.CharField(blank=True, max_length=10, null=True)),
                ('import_date', models.DateField(blank=True, null=True)),
                ('export_date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('group_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_type_member', to='mainapp.grouptype')),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_tel', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='ProgramName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'program_name',
            },
        ),
        migrations.CreateModel(
            name='RelStaffGroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_type_staff_group_type', to='mainapp.grouptype')),
            ],
            options={
                'db_table': 'rel_staff_group_type',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('memo', models.TextField(blank=True, null=True)),
                ('group_type', models.ManyToManyField(blank=True, null=True, related_name='group_type_staff', through='mainapp.RelStaffGroupType', to='mainapp.GroupType')),
                ('user', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.AddField(
            model_name='relstaffgrouptype',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_staff_group_type', to='mainapp.staff'),
        ),
        migrations.CreateModel(
            name='RelMemberProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(blank=True, choices=[('전화', '전화'), ('방문', '방문')], max_length=2, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_member_program', to='mainapp.member')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_member_program', to='mainapp.program')),
            ],
            options={
                'db_table': 'rel_member_program',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_program', through='mainapp.RelMemberProgram', to='mainapp.Member'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_name_program', to='mainapp.programname'),
        ),
        migrations.AddField(
            model_name='member',
            name='program',
            field=models.ManyToManyField(blank=True, null=True, related_name='program_member', through='mainapp.RelMemberProgram', to='mainapp.Program'),
        ),
        migrations.AddField(
            model_name='grouptype',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, related_name='staff_group_type', through='mainapp.RelStaffGroupType', to='mainapp.Staff'),
        ),
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('sul', models.BooleanField(blank=True, null=True)),
                ('bohoon', models.BooleanField(blank=True, null=True)),
                ('choosuk', models.BooleanField(blank=True, null=True)),
                ('junjukji', models.BooleanField(blank=True, null=True)),
                ('charun', models.BooleanField(blank=True, null=True)),
                ('etc1', models.BooleanField(blank=True, null=True)),
                ('etc2', models.BooleanField(blank=True, null=True)),
                ('etc3', models.BooleanField(blank=True, null=True)),
                ('explain', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_group_event', to='mainapp.member')),
            ],
            options={
                'db_table': 'group_event',
            },
        ),
        migrations.CreateModel(
            name='Counseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_counseling', to='mainapp.member')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_counseling', to='mainapp.staff')),
            ],
            options={
                'db_table': 'counseling',
            },
        ),
    ]
