# Generated by Django 3.2.6 on 2021-08-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptype',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staff_group_type', through='mainapp.RelStaffGroupType', to='mainapp.Staff'),
        ),
        migrations.AlterField(
            model_name='member',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='program_member', through='mainapp.RelMemberProgram', to='mainapp.Program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='member_program', through='mainapp.RelMemberProgram', to='mainapp.Member'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='group_type',
            field=models.ManyToManyField(blank=True, related_name='group_type_staff', through='mainapp.RelStaffGroupType', to='mainapp.GroupType'),
        ),
    ]
