# Generated by Django 3.2.6 on 2021-09-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210819_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupevent',
            name='event_created_date',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
