# Generated by Django 3.2.7 on 2021-09-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_groupevent_event_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
