# Generated by Django 3.2.7 on 2021-09-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_member_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pre_deleted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='yoo_gong_ja_rel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
