# Generated by Django 3.2.7 on 2021-09-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210911_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupevent',
            options={'ordering': ['-event_created_date', 'member']},
        ),
        migrations.AlterModelOptions(
            name='grouptype',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['group_type', 'name']},
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='explain',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
